name: emojis_null_safe
description: Emojis for Dart! This package contain all unicode 13.0 emojis (2020)!
version: 0.0.2
homepage: https://github.com/amebrahimi/emoji_null_safe

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
